listener: # Listener is the settings for the VastleX listener.
  host: 0.0.0.0
  port: 19132
lobby: # Lobby is the first server they get sent to when they join, if it is disabled they will not have a server and will eventually timeout unless you transfer them via your plugin.
  enabled: true
  host: 127.0.0.1
  port: 19133
fallback: # Fallback is the server they get transferred to when they get kicked from the server they were in (If enabled is set to false they get kicked).
  enabled: true
  host: 127.0.0.1
  port: 19133
minecraft: # Minecraft contains settings related to the Minecraft aspect of the proxy.
  auth: true
  motd: §l§cVastle§r§r§l§fX§r§r
  showversion: false
  maxplayers: 0
debug: # Debug contains features designed for debugging the proxy.
  logging: false # If set to true debug messages will be sent to the console.
  blocktranslating: true # Disable this if you are using all dragonfly servers (It is required for pretty much every other server software).
  profiling: # Profiling contains the different profilers you can use to debug the memory / cpu usage of the proxy.
    pprof: # https://github.com/google/pprof
      enabled: false
      address: ""
    gosivy: # https://github.com/nakabonne/gosivy
      enabled: false
      address: ""
security: # Security contains settings related to the security of the proxy.
  secret: 8780e692093b013ada99aa93e36e04cc9a619a6b5efa4a412f20cde8ee513062 # Secret is the shared secret between the Proxy and the Server to ensure unauthorized connections are coming from the proxy. (If you get the config from github please change the default secret)